name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build and test backend
        run: mvn clean verify
      - name: Upload backend test results
        uses: actions/upload-artifact@v4
        with:
          name: backend-allure-results
          path: backend/target/allure-results
      - name: Fail if Allure results missing (backend)
        run: |
          if [ ! -d "target/allure-results" ] || [ -z "$(ls -A target/allure-results 2>/dev/null)" ]; then
            echo "Allure results missing for backend!"; exit 1;
          fi

  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright browser dependencies
        run: npx playwright install-deps
      - name: Lint
        run: npm run lint
      - name: Build frontend
        run: npm run build
      # Start Next.js server in the background
      - name: Start Next.js server
        run: npm run start &
        env:
          NODE_ENV: production
      # Wait for Next.js to be ready
      - name: Wait for Next.js to be ready
        run: |
          for i in {1..30}; do
            nc -z localhost 3000 && echo "Next.js is up!" && exit 0
            echo "Waiting for Next.js..."
            sleep 2
          done
          echo "Next.js did not start in time" && exit 1
      - name: Run Java E2E tests
        run: mvn clean test
      - name: Upload frontend test results
        uses: actions/upload-artifact@v4
        with:
          name: frontend-allure-results
          path: frontend/target/allure-results
      - name: Fail if Allure results missing (frontend)
        run: |
          if [ ! -d "target/allure-results" ] || [ -z "$(ls -A target/allure-results 2>/dev/null)" ]; then
            echo "Allure results missing for frontend!"; exit 1;
          fi

  allure-report:
    needs: [build-backend, build-frontend]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download backend Allure results
        uses: actions/download-artifact@v4
        with:
          name: backend-allure-results
          path: backend/target/allure-results
      - name: Download frontend Allure results
        uses: actions/download-artifact@v4
        with:
          name: frontend-allure-results
          path: frontend/target/allure-results
      - name: Set up Allure
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -xzf allure-2.27.0.tgz
          sudo mv allure-2.27.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
      - name: Generate Allure report
        run: |
          mkdir -p allure-report
          allure generate backend/target/allure-results frontend/target/allure-results -o allure-report --clean
      - name: Upload Allure report artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
      - name: Add summary with Allure report link
        run: |
          echo "### [Allure Report](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/)" >> $GITHUB_STEP_SUMMARY 